Deployment/objects/Person__c.object
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Deployment/objects/Pet__c.object
<CustomObject>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OwnerPerson</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Pets</relationshipLabel>
        <relationshipName>Pets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dog</fullName>
                </value>
                <value>
                    <fullName>Cat</fullName>
                </value>
                <value>
                    <fullName>Birdy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Deployment/classes/PetAllowance.cls
public with sharing class PetAllowance {

    public static void allowPet(List<Pet__c> pets) {
        Set<Id> ownerIds = new Set<Id>();
        for(Pet__c pet : pets){
            ownerIds.add(pet.Owner__c);
        }
        List<Person__c> owners = [SELECT Id, Name, (SELECT Id, Type__c FROM Pets__r) FROM Person__c WHERE Id IN: ownerIds];
        for(Pet__c pet : pets){
            for(Person__c owner : owners){
                if(owner.Id.equals(pet.Owner__c)){
                    for(Pet__c existingPet : owner.Pets__r){
                        if(existingPet.Type__c == pet.Type__c){
                            pet.addError('Mother said, you have already a ' + pet.Type__c);
                        }
                    }
                }
            }
        }
    }
}