Deployment/objects/Person__c.object
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Deployment/objects/Toy__c.object
<CustomObject>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OwnerPerson</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Toys</relationshipLabel>
        <relationshipName>Toys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Doll</fullName>
                </value>
                <value>
                    <fullName>Car</fullName>
                </value>
                <value>
                    <fullName>LEGO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Toy</label>
    <nameField>
        <label>Toy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Deployment/classes/ToyPurchase.cls
public with sharing class ToyPurchase {

    public static void buyToy(List<Toy__c> toys) {
        Set<Id> ownerIds = new Set<Id>();
        for(Toy__c toy : toys){
            ownerIds.add(toy.Owner__c);
        }
        List<Person__c> owners = [SELECT Id, Name, (SELECT Id, Type__c FROM Toys__r) FROM Person__c WHERE Id IN: ownerIds];
        for(Toy__c toy : toys){
            for(Person__c owner : owners){
                if(owner.Id.equals(toy.Owner__c)){
                    toy.Name = owner.Name+'_'+toy.Type__c;
                    for(Toy__c existingToy : owner.toys__r){
                        if(existingToy.Type__c == toy.Type__c){
                            toy.addError('Mother said, you have already a ' + toy.Type__c);
                        }
                    }
                }
            }
        }
    }
}